App\Entity\Contact:
    attributes:
        id:
            groups: ['contact']
        nombres:
            groups: ['contact']
        email:
            groups: ['contact']
        comentario:
            groups: ['contact']
       
        

